---
title: "cluster table"
author: "George"
date: "3/30/2022"
output: pdf_document
keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)

load("data/combined_data_5min.Rdata")

d_allfeat <- d

# Remove fat_ed and mom_ed
d$time = NULL
d$fat_ed = NULL
d$mom_ed = NULL
```

Load clustered data.

```{r table, echo=F}
load("data/all_clusters_raw_lena_5mins.Rdata") # k-means 7 clusters

all_dat_cl <- all_dat_cl %>% 
  mutate(nap = ifelse(cds_ohs=="nap", 1, 0),
         cds = ifelse(cds_ohs==1, 1, 0),
         ohs = ifelse(cds_ohs==0 | cds_ohs=="split", 1, 0),
         #cluster = kfit$cluster
        ) %>% dplyr::select(-cds_ohs)
```

Merge demographic data, mostly to check whether clusters differ much by language.


```{r}
all_tab <- all_dat_cl %>% group_by(cluster) %>%
  #relocate(cluster, .before=AWC) %>%
  summarise(cluster = median(cluster), 
            N = n(),
            sleep = mean(nap),
            tCDS = mean(cds),
            ODS = mean(ohs),
            AWC = mean(AWC),
            CTC = mean(CTC),
            CVC = mean(CVC),
            noise = mean(noise),
            silence = mean(silence),
            distant = mean(distant),
            TV = mean(tv),
            meaningful = mean(meaningful)
            ) %>%
  mutate(cluster = as.factor(cluster))

# how many children are represented per cluster?
children_cl <- d %>% mutate(cluster = all_dat_cl$cluster) %>% 
  group_by(id, cluster) %>% summarise(n = n()) %>%
  group_by(cluster) %>% 
  summarise(Nclust=n())
# >=103 children per cluster, some with 135+

require(kableExtra)
#knitr::kable(all_tab %>% arrange(cds, ohs), digits=2, caption= "Means of LENA variables by cluster.")
#apa_table(all_tab %>% arrange(cds, ohs), digits=2, caption= "Means of LENA variables by cluster.") 

all_tab_reorder = all_tab[c(4,5, 6,1, 7,2,3),]

#all_tab_reorder %>% arrange(desc(CDS), desc(ODS)) 
all_tab_reorder %>%
  kbl(caption = "Means of LENA variables by cluster.", booktabs=T, digits=2) %>%
  #kable_classic(full_width = F, html_font = "Cambria") %>%
  column_spec(3, bold=c(T,T,F,F,F,F,F)) %>%
  column_spec(4, bold=c(F,F,T,T,F,F,F)) %>%
  column_spec(5, bold=c(F,F,F,F,T,T,T)) %>%
  column_spec(1, italic=T) 
```

